mirror_to_github:
  stage: deploy
  script:
    - git config --global user.email "racpast@gmail.com"
    - git config --global user.name "racpast"
    - git remote add github "https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/SyncTest.git"
    - git push --force github HEAD:main
  only:
    - main