name: Pull from GitLab

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Identity
        run: |
          git config --global user.email "racpast@gmail.com"
          git config --global user.name "racpast"

      - name: Pull from GitLab
        run: |
          git remote add gitlab "https://$GITLAB_USERNAME:$GITLAB_TOKEN@gitlab.com/$GITLAB_USERNAME/SyncTest.git"
          git fetch gitlab main
          
          git merge gitlab/main --allow-unrelated-histories --no-edit
          
          git push "https://$GH_USERNAME:$GH_TOKEN@github.com/$GH_USERNAME/SyncTest.git" HEAD:main
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
